load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//srcs:__subpackages__"])

cc_library(
    name = "market_data_publisher",
    hdrs = ["market_data_publisher.h"],
    deps = [
        "//lib:trade_message",
    ],
)
